apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-memcached
  labels:
    app: vpro-memcached
spec:
  selector:
    matchLabels:
      app: vpro-memcached
  replicas: 1
  template:
    metadata:
      labels:
        app: vpro-memcached
    spec:
      containers:
        - name: vpro-memcached
          image: memcached
          ports:
            - name: vpromc-port
              containerPort: 11211
